services:
  symfony:
    build:
      context: .
    container_name: symfony-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:@mysql:3306/todo_app?serverVersion=mariadb-10.4.11&charset=utf8mb4
    depends_on:
      - mysql
    networks:
      - to-do
    volumes:
      - .:/var/www/html
    command: >
      /bin/bash -c "
      until nc -z mysql 3306; do
        echo 'Waiting for MariaDB...';
        sleep 1;
      done;
      echo 'MariaDB is up - executing commands';
      composer install &&
      php bin/console doctrine:schema:create --no-interaction &&
      php bin/console doctrine:migrations:migrate --no-interaction &&
      php -S 0.0.0.0:8000 -t public"

  mysql:
    image: mariadb:10.4
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=todo_app
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - to-do
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

networks:
  to-do:
    driver: bridge
    name: to-do

volumes:
  mysql-data:
